[platform]
platform = espressif32
framework = arduino
board = esp32dev
upload_speed = 921600
monitor_speed = 921600
lib_deps =
  ArduinoJson
  git+https://github.com/matthijskooijman/arduino-dsmr#5a0b558
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++2a
  -Wall
  -Wextra
  -Werror

[env:esp32dev]
extends = platform

[env:unit_tests]
platform = native
test_framework = googletest
build_src_filter = *
