[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev
upload_speed = 921600
upload_port = COM4
monitor_speed = 921600
monitor_port = COM4
lib_deps =
  ArduinoJson
  git+https://github.com/matthijskooijman/arduino-dsmr#5a0b558
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++2a
  -Wall
  -Wextra
  -Werror
